# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: WRT-TEST

on:
  workflow_dispatch:
    inputs:
      CONFIG:
        default: 'MT7981-360T7'
        required: true
        type: choice
        options:
          - MT7981-360T7
          - MT7981
          - MT7986
          - TEST
      SOURCE:
        default: 'Yuzhii0718/immortalwrt-mt798x-6.6-padavanonly'
        required: true
        type: choice
        options:
          - Yuzhii0718/immortalwrt-mt798x-6.6-padavanonly
          - chasey-dev/immortalwrt-mt798x-rebase
      BRANCH:
        default: 'openwrt-24.10-6.6'
        required: true
        type: string
      PACKAGE:
        required: false
        type: string
      TEST:
        description: 'Generate config only, do not compile firmware'
        default: true
        required: true
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{ inputs.CONFIG }}
    uses: ./.github/workflows/WRT-CORE.yml
    secrets: inherit
    with:
      WRT_CONFIG: ${{ inputs.CONFIG }}
      WRT_THEME: argon
      WRT_NAME: 360T7
      WRT_SSID: ImmortalWrt-2.4G / ImmortalWrt-5G
      WRT_WORD: none
      WRT_IP: 192.168.1.1
      WRT_PW: none
      WRT_REPO: https://github.com/${{ inputs.SOURCE }}.git
      WRT_BRANCH: ${{ inputs.BRANCH }}
      WRT_SOURCE: ${{ inputs.SOURCE }}
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST && 'true' || 'false' }}
